"""create_users_table_with_address

Revision ID: 082f1776c3a0
Revises: 58c481690bf4
Create Date: 2026-02-26 22:49:59.202197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082f1776c3a0'
down_revision: Union[str, None] = '58c481690bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telefone', sa.String(length=20), nullable=True))
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'telefone_contato',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'endereco_logradouro',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'endereco_cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'endereco_estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('users', 'endereco_regiao',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('ix_users_cpf', table_name='users')
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_recuperacao_token'), 'users', ['recuperacao_token'], unique=False)
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_users_recuperacao_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.create_index('ix_users_cpf', 'users', ['cpf'], unique=False)
    op.alter_column('users', 'endereco_regiao',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'endereco_estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('users', 'endereco_cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'endereco_logradouro',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'telefone_contato',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'telefone')
    # ### end Alembic commands ###
