"""adiciona_tabela_super_admins

Revision ID: 10c1f0e2b542
Revises: d514aa14141a
Create Date: 2026-02-25 22:33:38.528827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c1f0e2b542'
down_revision: Union[str, None] = 'd514aa14141a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_admins',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='superadminstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_por', sa.UUID(), nullable=True),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.Column('deletado_por', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_super_admins_email'), 'super_admins', ['email'], unique=True)
    op.create_index(op.f('ix_super_admins_id'), 'super_admins', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_super_admins_id'), table_name='super_admins')
    op.drop_index(op.f('ix_super_admins_email'), table_name='super_admins')
    op.drop_table('super_admins')
    # ### end Alembic commands ###
