"""create_service_records_table

Revision ID: 1bcac3954402
Revises: 889d1ad42d67
Create Date: 2026-03-04 16:29:22.829193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcac3954402'
down_revision: Union[str, None] = '889d1ad42d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('profissional_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('AVALIACAO_INICIAL', 'NOTA_SESSAO', 'RECOMENDACAO', 'DOCUMENTO', 'INTERNO', name='servicerecordtype'), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('assinado', sa.Boolean(), nullable=False),
    sa.Column('data_assinatura', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('alterado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profissional_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_records_appointment_id'), 'service_records', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_service_records_customer_id'), 'service_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_service_records_id'), 'service_records', ['id'], unique=False)
    op.create_index(op.f('ix_service_records_profissional_id'), 'service_records', ['profissional_id'], unique=False)
    op.create_index(op.f('ix_service_records_tenant_id'), 'service_records', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_records_tenant_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_profissional_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_customer_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_appointment_id'), table_name='service_records')
    op.drop_table('service_records')
    # ### end Alembic commands ###
