"""create_appointments_table

Revision ID: 39af65e91b5f
Revises: d100d279604a
Create Date: 2026-02-27 22:35:33.321733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39af65e91b5f'
down_revision: Union[str, None] = 'd100d279604a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('customer_id', sa.UUID(), nullable=False))
    op.alter_column('appointments', 'servico_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('appointments', 'duracao_aplicada',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'preco_aplicado',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('appointments', 'alterado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_appointments_cliente_id', table_name='appointments')
    op.create_index(op.f('ix_appointments_customer_id'), 'appointments', ['customer_id'], unique=False)
    op.drop_constraint('appointments_profissional_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_tenant_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_servico_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_recurso_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_cliente_id_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['profissional_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('appointments', 'criado_por')
    op.drop_column('appointments', 'cliente_id')
    op.drop_column('appointments', 'deletado_em')
    op.drop_column('appointments', 'deletado_por')
    op.drop_column('appointments', 'alterado_por')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('alterado_por', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('deletado_por', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('deletado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('cliente_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('criado_por', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_cliente_id_fkey', 'appointments', 'users', ['cliente_id'], ['id'])
    op.create_foreign_key('appointments_recurso_id_fkey', 'appointments', 'resources', ['recurso_id'], ['id'])
    op.create_foreign_key('appointments_servico_id_fkey', 'appointments', 'services', ['servico_id'], ['id'])
    op.create_foreign_key('appointments_tenant_id_fkey', 'appointments', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key('appointments_profissional_id_fkey', 'appointments', 'users', ['profissional_id'], ['id'])
    op.drop_index(op.f('ix_appointments_customer_id'), table_name='appointments')
    op.create_index('ix_appointments_cliente_id', 'appointments', ['cliente_id'], unique=False)
    op.alter_column('appointments', 'alterado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('appointments', 'preco_aplicado',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('appointments', 'duracao_aplicada',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'servico_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('appointments', 'customer_id')
    # ### end Alembic commands ###
