"""adiciona_config_visuais

Revision ID: 3b504cd5f007
Revises: 4ab14228d56c
Create Date: 2026-03-26 17:27:53.771238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b504cd5f007'
down_revision: Union[str, None] = '4ab14228d56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('PENDENTE', 'CONFIRMADO', 'CONCLUIDO', 'CANCELADO_CLIENTE', 'CANCELADO_PROFISSIONAL', 'NO_SHOW', name='appointmentstatus'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_appointments_data_hora_fim', table_name='appointments')
    op.create_foreign_key(None, 'appointments', 'services', ['servico_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'users', ['alterado_por'], ['id'])
    op.create_foreign_key(None, 'appointments', 'users', ['criado_por'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_index('ix_appointments_data_hora_fim', 'appointments', ['data_hora_fim'], unique=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDENTE', 'CONFIRMADO', 'CONCLUIDO', 'CANCELADO_CLIENTE', 'CANCELADO_PROFISSIONAL', 'NO_SHOW', name='appointmentstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
