"""create_resources_table

Revision ID: 402a90d4cc31
Revises: b254304b2c8f
Create Date: 2026-02-28 01:43:45.196831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '402a90d4cc31'
down_revision: Union[str, None] = 'b254304b2c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'alterado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_resources_nome'), 'resources', ['nome'], unique=False)
    op.drop_constraint('resources_tenant_id_fkey', 'resources', type_='foreignkey')
    op.create_foreign_key(None, 'resources', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('resources', 'criado_por')
    op.drop_column('resources', 'deletado_por')
    op.drop_column('resources', 'alterado_por')
    op.drop_column('resources', 'deletado_em')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('deletado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('resources', sa.Column('alterado_por', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('resources', sa.Column('deletado_por', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('resources', sa.Column('criado_por', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.create_foreign_key('resources_tenant_id_fkey', 'resources', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_resources_nome'), table_name='resources')
    op.alter_column('resources', 'alterado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
