"""add_audit_and_status_to_customers

Revision ID: 4ab14228d56c
Revises: c350790c3520
Create Date: 2026-03-06 13:41:20.073639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab14228d56c'
down_revision: Union[str, None] = 'c350790c3520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DO $$ BEGIN CREATE TYPE customerstatus AS ENUM ('ativo', 'inativo', 'ATIVO', 'INATIVO'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='customerstatus'), server_default='ativo', nullable=False))
    op.add_column('customers', sa.Column('criado_por', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('alterado_por', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('deletado_em', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('deletado_por', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'deletado_por')
    op.drop_column('customers', 'deletado_em')
    op.drop_column('customers', 'alterado_por')
    op.drop_column('customers', 'criado_por')
    op.drop_column('customers', 'status')
    # ### end Alembic commands ###
