"""add_grupo_recorrencia_id

Revision ID: 51c0a82f7616
Revises: a9370e6c4f4b
Create Date: 2026-03-03 01:49:11.609594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c0a82f7616'
down_revision: Union[str, None] = 'a9370e6c4f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('grupo_recorrencia_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_appointments_grupo_recorrencia_id'), 'appointments', ['grupo_recorrencia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_grupo_recorrencia_id'), table_name='appointments')
    op.drop_column('appointments', 'grupo_recorrencia_id')
    # ### end Alembic commands ###
