"""create_waitlist_table

Revision ID: 6361239390ec
Revises: afd4be519312
Create Date: 2026-03-27 12:24:51.015582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6361239390ec'
down_revision: Union[str, None] = 'afd4be519312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('servico_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=True),
    sa.Column('data_hora_inicio_desejada', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim_desejada', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('alterado_por', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('alterado_em', sa.DateTime(), nullable=False),
    sa.Column('notificado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alterado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlists_customer_id'), 'waitlists', ['customer_id'], unique=False)
    op.create_index(op.f('ix_waitlists_data_hora_fim_desejada'), 'waitlists', ['data_hora_fim_desejada'], unique=False)
    op.create_index(op.f('ix_waitlists_data_hora_inicio_desejada'), 'waitlists', ['data_hora_inicio_desejada'], unique=False)
    op.create_index(op.f('ix_waitlists_id'), 'waitlists', ['id'], unique=False)
    op.create_index(op.f('ix_waitlists_professional_id'), 'waitlists', ['professional_id'], unique=False)
    op.create_index(op.f('ix_waitlists_servico_id'), 'waitlists', ['servico_id'], unique=False)
    op.create_index(op.f('ix_waitlists_status'), 'waitlists', ['status'], unique=False)
    op.create_index(op.f('ix_waitlists_tenant_id'), 'waitlists', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlists_tenant_id'), table_name='waitlists')
    op.drop_index(op.f('ix_waitlists_status'), table_name='waitlists')
    op.drop_index(op.f('ix_waitlists_servico_id'), table_name='waitlists')
    op.drop_index(op.f('ix_waitlists_professional_id'), table_name='waitlists')
    op.drop_index(op.f('ix_waitlists_id'), table_name='waitlists')
    op.drop_index(op.f('ix_waitlists_data_hora_inicio_desejada'), table_name='waitlists')
    op.drop_index(op.f('ix_waitlists_data_hora_fim_desejada'), table_name='waitlists')
    op.drop_index(op.f('ix_waitlists_customer_id'), table_name='waitlists')
    op.drop_table('waitlists')
    # ### end Alembic commands ###
