"""add_audit_columns_to_services

Revision ID: 72405d23d66a
Revises: 471738939a94
Create Date: 2026-03-06 11:24:09.116997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72405d23d66a'
down_revision: Union[str, None] = '471738939a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('criado_por', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('alterado_por', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('deletado_em', sa.DateTime(), nullable=True))
    op.add_column('services', sa.Column('deletado_por', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'deletado_por')
    op.drop_column('services', 'deletado_em')
    op.drop_column('services', 'alterado_por')
    op.drop_column('services', 'criado_por')
    # ### end Alembic commands ###
