"""sincroniza_colunas_appointments

Revision ID: 889d1ad42d67
Revises: 9086aa4a0a82
Create Date: 2026-03-04 15:58:59.996191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '889d1ad42d67'
down_revision: Union[str, None] = '9086aa4a0a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Garantimos que o tipo ENUM existe no banco antes de tentar converter a coluna
    appointment_status = postgresql.ENUM('PENDENTE', 'CONFIRMADO', 'CONCLUIDO', 'CANCELADO_CLIENTE', 'CANCELADO_PROFISSIONAL', 'NO_SHOW', name='appointmentstatus')
    appointment_status.create(op.get_bind(), checkfirst=True)

    op.add_column('appointments', sa.Column('duracao_aplicada', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('preco_aplicado', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('appointments', sa.Column('observacoes_cliente', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('observacoes_internas', sa.Text(), nullable=True))
    op.alter_column('appointments', 'servico_id',
               existing_type=sa.UUID(),
               nullable=True)
               
    # 👇 A CORREÇÃO: Adicionamos o postgresql_using para autorizar o cast dos dados
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDENTE', 'CONFIRMADO', 'CONCLUIDO', 'CANCELADO_CLIENTE', 'CANCELADO_PROFISSIONAL', 'NO_SHOW', name='appointmentstatus'),
               existing_nullable=False,
               postgresql_using='status::appointmentstatus')
               
    op.create_index(op.f('ix_appointments_data_hora_fim'), 'appointments', ['data_hora_fim'], unique=False)
    op.drop_constraint('appointments_recurso_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_servico_id_fkey', 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'observacoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('appointments_servico_id_fkey', 'appointments', 'services', ['servico_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('appointments_recurso_id_fkey', 'appointments', 'resources', ['recurso_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_appointments_data_hora_fim'), table_name='appointments')
    
    # 👇 O INVERSO: Transformando ENUM de volta para texto em caso de rollback
    op.alter_column('appointments', 'status',
               existing_type=sa.Enum('PENDENTE', 'CONFIRMADO', 'CONCLUIDO', 'CANCELADO_CLIENTE', 'CANCELADO_PROFISSIONAL', 'NO_SHOW', name='appointmentstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='status::text')
               
    op.alter_column('appointments', 'servico_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('appointments', 'observacoes_internas')
    op.drop_column('appointments', 'observacoes_cliente')
    op.drop_column('appointments', 'preco_aplicado')
    op.drop_column('appointments', 'duracao_aplicada')
    
    appointment_status = postgresql.ENUM('PENDENTE', 'CONFIRMADO', 'CONCLUIDO', 'CANCELADO_CLIENTE', 'CANCELADO_PROFISSIONAL', 'NO_SHOW', name='appointmentstatus')
    appointment_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
