"""reset_appointments_table_string_status

Revision ID: 9086aa4a0a82
Revises: 51c0a82f7616
Create Date: 2026-03-03 13:07:17.148841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9086aa4a0a82'
down_revision: Union[str, None] = '51c0a82f7616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('PENDENTE', 'CONFIRMADO', 'CONCLUIDO', 'CANCELADO_CLIENTE', 'CANCELADO_PROFISSIONAL', 'NO_SHOW', name='appointmentstatus'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDENTE', 'CONFIRMADO', 'CONCLUIDO', 'CANCELADO_CLIENTE', 'CANCELADO_PROFISSIONAL', 'NO_SHOW', name='appointmentstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
