"""add_service_and_resource_fks_to_appointments

Revision ID: a9370e6c4f4b
Revises: beb870b0e432
Create Date: 2026-03-03 01:35:09.669594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9370e6c4f4b'
down_revision: Union[str, None] = 'beb870b0e432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('professional_id', sa.UUID(), nullable=False))
    op.add_column('appointments', sa.Column('observacoes', sa.Text(), nullable=True))
    op.alter_column('appointments', 'servico_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_appointments_data_hora_fim', table_name='appointments')
    op.drop_index('ix_appointments_grupo_recorrencia_id', table_name='appointments')
    op.drop_index('ix_appointments_profissional_id', table_name='appointments')
    op.create_index(op.f('ix_appointments_professional_id'), 'appointments', ['professional_id'], unique=False)
    op.drop_constraint('appointments_profissional_id_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'resources', ['recurso_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'appointments', 'users', ['professional_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'services', ['servico_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('appointments', 'observacoes_cliente')
    op.drop_column('appointments', 'observacoes_internas')
    op.drop_column('appointments', 'preco_aplicado')
    op.drop_column('appointments', 'grupo_recorrencia_id')
    op.drop_column('appointments', 'duracao_aplicada')
    op.drop_column('appointments', 'profissional_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('profissional_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('duracao_aplicada', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('grupo_recorrencia_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('preco_aplicado', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('observacoes_internas', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('observacoes_cliente', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_profissional_id_fkey', 'appointments', 'users', ['profissional_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_appointments_professional_id'), table_name='appointments')
    op.create_index('ix_appointments_profissional_id', 'appointments', ['profissional_id'], unique=False)
    op.create_index('ix_appointments_grupo_recorrencia_id', 'appointments', ['grupo_recorrencia_id'], unique=False)
    op.create_index('ix_appointments_data_hora_fim', 'appointments', ['data_hora_fim'], unique=False)
    op.alter_column('appointments', 'servico_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('appointments', 'observacoes')
    op.drop_column('appointments', 'professional_id')
    # ### end Alembic commands ###
