"""adiciona_coluna_anexos_em_service_records

Revision ID: b11e48711c78
Revises: 01399b89eaef
Create Date: 2026-03-27 23:46:39.163985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b11e48711c78'
down_revision: Union[str, None] = '01399b89eaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_records', sa.Column('anexos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_records', 'anexos')
    # ### end Alembic commands ###
