"""create_services_table

Revision ID: b254304b2c8f
Revises: 39af65e91b5f
Create Date: 2026-02-27 23:06:57.654984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b254304b2c8f'
down_revision: Union[str, None] = '39af65e91b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'alterado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_services_nome'), 'services', ['nome'], unique=False)
    op.drop_constraint('services_tenant_id_fkey', 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('services', 'alterado_por')
    op.drop_column('services', 'criado_por')
    op.drop_column('services', 'deletado_por')
    op.drop_column('services', 'deletado_em')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('deletado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('deletado_por', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('criado_por', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('alterado_por', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key('services_tenant_id_fkey', 'services', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_services_nome'), table_name='services')
    op.alter_column('services', 'alterado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
