"""create_import_staging_tables

Revision ID: beb870b0e432
Revises: 402a90d4cc31
Create Date: 2026-02-28 05:53:20.923964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'beb870b0e432'
down_revision: Union[str, None] = '402a90d4cc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Quem fez o upload'),
    sa.Column('entity_type', sa.Enum('CUSTOMER', 'PROFESSIONAL', 'SERVICE', 'RESOURCE', name='importentitytype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'WAITING_APPROVAL', 'COMPLETED', 'FAILED', name='importbatchstatus'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('alterado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_id'), 'import_batches', ['id'], unique=False)
    op.create_index(op.f('ix_import_batches_tenant_id'), 'import_batches', ['tenant_id'], unique=False)
    op.create_table('import_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False, comment='Numero da linha no arquivo original'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Os dados exatos que vieram na linha'),
    sa.Column('status', sa.Enum('PENDING', 'VALID', 'INVALID', 'DUPLICATED', 'IMPORTED', 'IGNORED', name='importrowstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Detalhes do erro'),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('alterado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_rows_batch_id'), 'import_rows', ['batch_id'], unique=False)
    op.create_index(op.f('ix_import_rows_id'), 'import_rows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_rows_id'), table_name='import_rows')
    op.drop_index(op.f('ix_import_rows_batch_id'), table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index(op.f('ix_import_batches_tenant_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_id'), table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
