"""add_audit_columns_to_resources

Revision ID: c350790c3520
Revises: 72405d23d66a
Create Date: 2026-03-06 13:22:43.296195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c350790c3520'
down_revision: Union[str, None] = '72405d23d66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('criado_por', sa.String(length=255), nullable=True))
    op.add_column('resources', sa.Column('alterado_por', sa.String(length=255), nullable=True))
    op.add_column('resources', sa.Column('deletado_em', sa.DateTime(), nullable=True))
    op.add_column('resources', sa.Column('deletado_por', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'deletado_por')
    op.drop_column('resources', 'deletado_em')
    op.drop_column('resources', 'alterado_por')
    op.drop_column('resources', 'criado_por')
    # ### end Alembic commands ###
