"""cria_motor_de_mensageria

Revision ID: d2b75cc8c299
Revises: b11e48711c78
Create Date: 2026-03-28 05:35:49.668878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b75cc8c299'
down_revision: Union[str, None] = 'b11e48711c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('codigo_interno', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('canal', sa.Enum('IN_APP', 'EMAIL', 'WHATSAPP', 'TELEGRAM', name='notificationchannel'), nullable=False),
    sa.Column('assunto', sa.String(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_templates_codigo_interno'), 'notification_templates', ['codigo_interno'], unique=False)
    op.create_index(op.f('ix_notification_templates_id'), 'notification_templates', ['id'], unique=False)
    op.create_index(op.f('ix_notification_templates_tenant_id'), 'notification_templates', ['tenant_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('remetente_id', sa.UUID(), nullable=True),
    sa.Column('destinatario_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('canal', sa.Enum('IN_APP', 'EMAIL', 'WHATSAPP', 'TELEGRAM', name='notificationchannel'), nullable=False),
    sa.Column('assunto', sa.String(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NA_FILA', 'PROCESSANDO', 'PROCESSADA', 'FALHA', name='notificationstatus'), nullable=False),
    sa.Column('erro_log', sa.Text(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('processado_em', sa.DateTime(), nullable=True),
    sa.Column('lido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destinatario_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['notification_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['remetente_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_customer_id'), 'notification_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_destinatario_id'), 'notification_logs', ['destinatario_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_id'), 'notification_logs', ['id'], unique=False)
    op.create_index(op.f('ix_notification_logs_lida'), 'notification_logs', ['lida'], unique=False)
    op.create_index(op.f('ix_notification_logs_status'), 'notification_logs', ['status'], unique=False)
    op.create_index(op.f('ix_notification_logs_tenant_id'), 'notification_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_logs_tenant_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_status'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_lida'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_destinatario_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_customer_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_notification_templates_tenant_id'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_id'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_codigo_interno'), table_name='notification_templates')
    op.drop_table('notification_templates')
    # ### end Alembic commands ###
