"""criacao_das_5_tabelas_iniciais

Revision ID: d514aa14141a
Revises: 
Create Date: 2026-02-25 22:18:10.370077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd514aa14141a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('codigo_visual', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('PHASE_IN', 'ATIVO', 'PHASE_OUT', 'INATIVO', name='tenantstatus'), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('segmento_atuacao', sa.String(length=100), nullable=False),
    sa.Column('fuso_horario', sa.String(length=50), nullable=False),
    sa.Column('endereco_logradouro', sa.String(length=255), nullable=False),
    sa.Column('endereco_cidade', sa.String(length=100), nullable=False),
    sa.Column('endereco_estado', sa.String(length=2), nullable=False),
    sa.Column('endereco_regiao', sa.String(length=50), nullable=False),
    sa.Column('site_url', sa.String(length=255), nullable=False),
    sa.Column('email_contato', sa.String(length=255), nullable=False),
    sa.Column('telefone_contato', sa.String(length=20), nullable=False),
    sa.Column('dominio_interno', sa.String(length=100), nullable=False),
    sa.Column('url_externa', sa.String(length=255), nullable=False),
    sa.Column('logotipo_url', sa.String(length=500), nullable=False),
    sa.Column('validade_assinatura', sa.DateTime(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_por', sa.UUID(), nullable=True),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.Column('deletado_por', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_cnpj'), 'tenants', ['cnpj'], unique=True)
    op.create_index(op.f('ix_tenants_codigo_visual'), 'tenants', ['codigo_visual'], unique=True)
    op.create_index(op.f('ix_tenants_dominio_interno'), 'tenants', ['dominio_interno'], unique=True)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('resources',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='resourcestatus'), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('FISICO', 'ONLINE', name='resourcetype'), nullable=False),
    sa.Column('capacidade_maxima', sa.Integer(), nullable=False),
    sa.Column('requer_aprovacao', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_por', sa.UUID(), nullable=True),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.Column('deletado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_tenant_id'), 'resources', ['tenant_id'], unique=False)
    op.create_table('services',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='servicestatus'), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('imagem_url', sa.String(length=500), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_por', sa.UUID(), nullable=True),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.Column('deletado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_tenant_id'), 'services', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'ATIVO', 'INATIVO', name='userstatus'), nullable=False),
    sa.Column('papel', sa.Enum('TENANT_ADMIN', 'PROFISSIONAL', 'CLIENTE', name='userrole'), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('recuperacao_token', sa.String(length=100), nullable=True),
    sa.Column('recuperacao_expira', sa.DateTime(), nullable=True),
    sa.Column('endereco_logradouro', sa.String(length=255), nullable=False),
    sa.Column('endereco_cidade', sa.String(length=100), nullable=False),
    sa.Column('endereco_estado', sa.String(length=2), nullable=False),
    sa.Column('endereco_regiao', sa.String(length=50), nullable=False),
    sa.Column('telefone_contato', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_por', sa.UUID(), nullable=True),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.Column('deletado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('appointments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('profissional_id', sa.UUID(), nullable=False),
    sa.Column('servico_id', sa.UUID(), nullable=False),
    sa.Column('recurso_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'CONFIRMADO', 'CONCLUIDO', 'CANCELADO_CLIENTE', 'CANCELADO_PROFISSIONAL', 'NO_SHOW', name='appointmentstatus'), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=False),
    sa.Column('duracao_aplicada', sa.Integer(), nullable=False),
    sa.Column('preco_aplicado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('grupo_recorrencia_id', sa.UUID(), nullable=True),
    sa.Column('observacoes_cliente', sa.Text(), nullable=True),
    sa.Column('observacoes_internas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_por', sa.UUID(), nullable=True),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.Column('deletado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recurso_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_cliente_id'), 'appointments', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_appointments_data_hora_fim'), 'appointments', ['data_hora_fim'], unique=False)
    op.create_index(op.f('ix_appointments_data_hora_inicio'), 'appointments', ['data_hora_inicio'], unique=False)
    op.create_index(op.f('ix_appointments_grupo_recorrencia_id'), 'appointments', ['grupo_recorrencia_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_profissional_id'), 'appointments', ['profissional_id'], unique=False)
    op.create_index(op.f('ix_appointments_recurso_id'), 'appointments', ['recurso_id'], unique=False)
    op.create_index(op.f('ix_appointments_servico_id'), 'appointments', ['servico_id'], unique=False)
    op.create_index(op.f('ix_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_tenant_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_servico_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_recurso_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_profissional_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_grupo_recorrencia_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_data_hora_inicio'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_data_hora_fim'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_cliente_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_tenant_id'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_resources_tenant_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_dominio_interno'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_codigo_visual'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_cnpj'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
